name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - x64
          - arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup asdf
        uses: asdf-vm/actions/install@v4

      - name: Install herdr
        run: |
          asdf install herdr latest
          asdf global herdr latest

      - name: Verify installation
        run: |
          herdr --version
          asdf list herdr
